Fixing tweaks
Connecting to Couchbase was wrong and caused

Error: Failed to schedule connection
    at Object.exports.connect
(/Users/apolion/Developer/ntwitter-node-couchbase/node_modules/couchbase
/lib/couchbase.js:109:22)